version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-major:
        update-types:
          - major
        patterns:
          - "*"
      npm-non-major:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-major:
        update-types:
          - major
        patterns:
          - "*"
      github-actions-non-major:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
